### ISSUE TITLE
Anonaddy app

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [anonaddy/anonaddy#100]
Hi i saw that fdroid has an AnonAddy app, but i didnt see any blog post about this. Is this an official app?

**Comment by willbrowningme** [comment]
The AnonAddy Android app by [Stjin](https://twitter.com/Stjinchan) is unofficial, however I was in talks with the developer during its development and made some tweaks to the API to help. It is also [open-source](https://gitlab.com/Stjin/anonaddy-android), I use it myself and it's great.

I'm not familiar with mobile development which is why I haven't created an official mobile app myself.
