### ISSUE TITLE
jan 12th update breaks hey.com screening

### ISSUE THREAD

**Issue by AdnanTheExcellent** [anonaddy/anonaddy#124]
I'm not sure if you're familiar with hey.com, but they have a feature where you have to screen every unique email address that emails you before you can see their emails in your "imbox". Ive been using both anonaddy and hey.com for months with no problems until the jan 12th update. since then, for certain sites, it treats the same email as coming from different senders, and i 
have to screen every email sent from them. Here is an example of two emails from chase that are waiting to be screened, even though i've already screened that email in the past, and they are showing as coming from two different senders. 

It would be great if there could be any way to get hey.com's intended functionality working again.

Adnan

![image](https://user-images.githubusercontent.com/943069/106028681-17b94e80-6081-11eb-9028-268d3e933c07.png)

**Comment by willbrowningme** [comment]
Hmm it looks like it is because the "From:" header address is slightly different which must be because Chase has a different (or unique) "Reply-to:" header set on their original emails.

This issue will only occur when senders set a different/unique "Reply-to:" header on their emails, that is what is causing the "From:" address to have a different extension.

Do you only notice this issue with Chase?

I removed the "Reply-to:" header on forwarded emails and set it as the "From:" header because users were having issues with Gmail not respecting the "Reply-to:" header when they clicked the reply button.

I'll have a think about a solution to this, it would be good if hey.com could add an option to treat senders as the same email even if they have a different extension. Since if an email comes from "will+xyz@example.com" it's still the same sender as "will+abc@example.com".

**Comment by AdnanTheExcellent** [comment]
It's not just chase. I can message hey.com and ask them about it but I'm not really an expert on the subject so i might not be the right person to ask. I can file a bug issue with the dupe senders and see what they say.

**Comment by willbrowningme** [comment]
It's not the fault of the sender since many companies send email from say "company@example.com" but then they add a unique "Reply-to:" header so that if the customer replies they can act acordingly and instantly know which customer it is etc.

Perhaps I could add an option in settings to add back in the "Reply-to:" header on forwarded emails and keep the "From:" header as just the alias.

**Comment by AdnanTheExcellent** [comment]
Checking in on this. I did not hear back form hey.com when i reported my issue with them. Any plans to address?

**Comment by willbrowningme** [comment]
I will try to add the option to use the old email headers this week.

**Comment by willbrowningme** [comment]
Just pushed an update adding this option. It's in account settings under the heading "Use Reply-To Header For Replying".

Please give it a try.

**Comment by AdnanTheExcellent** [comment]
thanks! i'll let you know when i start getting more emails if this fixes things

**Comment by AdnanTheExcellent** [comment]
Things are looking good with the update. thanks!
