### ISSUE TITLE
DKIM computed bodyhash fails when used with encryption

### ISSUE THREAD

**Issue by anonaddy** [anonaddy/anonaddy#14]
Emails forwarded to custom domains (with sending verified) need to be signed by DKIM (selector dk1 or dk2).

This fails to pass DKIM checks when the email is also encrypted using GPG encryption.

DKIM checks fail due to the "Computed body hash is different from the expected one".

At the moment I've set it to not sign outgoing messages with DKIM for custom domains if they are also encrypted until I can find a solution.

**Comment by erik-h** [comment]
@anonaddy Any updates on this issue? I'm loving forwarding using my custom domain, but it'd be great to be also able to enable GPG encryption again.

**Comment by anonaddy** [comment]
@erik-h will look into this at the start of next week to see if I can find a solution. Thanks for reminding me.

**Comment by erik-h** [comment]
@anonaddy Awesome, thanks for the response!

**Comment by willbrowningme** [comment]
@erik-h This issue has now been fixed in the latest release.

It was solved by updating some LFs - `\n` to CRLFs - `\r\n`.

[https://github.com/anonaddy/anonaddy/commit/3056f5aed4ffff8fd0f688869433fafdcea648ab#diff-bc5a3d7c8332409aed797d25d7cdd2da](https://github.com/anonaddy/anonaddy/commit/3056f5aed4ffff8fd0f688869433fafdcea648ab#diff-bc5a3d7c8332409aed797d25d7cdd2da)

**Comment by erik-h** [comment]
@willbrowningme Ah I see, awesome, thanks again!
