### ISSUE TITLE
Replies to forwarded mails rejected

### ISSUE THREAD

**Issue by Flash1232** [anonaddy/anonaddy#157]
So I noticed that as of today, I am no longer able to reply to mails sent to my alias on app.anonaddy.com.

Instead, my mail provider would reject my outgoing reply and send me this:

> Reporting-MTA: dns; smtpauths.xxxproviderxxx.com [xxx.xxx.xxx.xxx]
> Received-From-MTA: dns; [192.168.0.20] [xxx.xxx.xxx.xxx]
> Arrival-Date: Wed, 26 May 2021 16:30:00 +0200
> 
> 
> Final-recipient: rfc822; blabla+help=domain.io@anonaddy.me
> Diagnostic-Code: smtp; 554 5.7.1 Rejected due to potential send/reply spoof attempt, make sure your sending domain has a DMARC policy
> 
> Last-attempt-Date: Wed, 26 May 2021 16:34:00 +0200

I tried replying from both my verified default recipient address and some other address.

Any clues?

EDIT: Sorry, I messed up.

**Comment by willbrowningme** [comment]
Apologies, I was testing new checks specifically for when replying or sending from an alias in order to protect aliases against spoofed sends/replies.

I've just disabled these checks but will be adding them again shortly.

These new checks will only apply to replying or sending from an alias and mean that your recipient email must pass DMARC checks to ensure that it is not a spoofed email. 

If your recipient on AnonAddy is using your own domain then please make sure you add a DMARC policy to it along with SPF and DKIM records.

To learn more about DMARC please see this site - [https://dmarc.org/](https://dmarc.org/).

If your recipient is with a popular mail service provider for example: Gmail, Outlook, Tutanota, Mailbox.org, Protonmail etc. then they will already have a DMARC policy in place so you do not need to take any action.

I've just updated the FAQ to address this - https://anonaddy.com/faq/#im-trying-to-reply-send-from-an-alias-but-it-is-rejected-whats-wrong
