### ISSUE TITLE
Keys not matching

### ISSUE THREAD

**Issue by subseaalex** [anonaddy/anonaddy#164]
Hi,

Can you explain why keys are not matching from mailer@annonaddy.me?

I am getting error
"Encrypted but end to end key did not match the sender"

**Comment by willbrowningme** [comment]
This is because your email client is using the From: header to check the key's identity.

However the From: header on AnonAddy is set to the alias email address.

It would not be feasible to add every alias email addresss as an identity to the "mailer@anonaddy.me" signing key. It also isn't really feasible to create a new signing key for every single alias so that it matches.

At the moment I'm not sure if there is any solution for this, except for sending every single forwarded email from "mailer@anonaddy.me" but then this would break many users mail filters etc.

I will have a think and see if I can come up with anything.

**Comment by subseaalex** [comment]
Thanks. Basically, key identity has to match allias email to work. Maybe ok for few keys, I can see this being a issue.

**Comment by willbrowningme** [comment]
Closing this for now as there is no solution to this issue that I'm aware of that would allow emails to be forwarded from aliases whilst having an exact identity match for the signing key.

**Comment by xyhhx** [comment]
> except for sending every single forwarded email from "[mailer@anonaddy.me](mailto:mailer@anonaddy.me)" but then this would break many users mail filters etc.

Can you make this a configurable option at least? Then, along with the `Reply-To:` header, a filter could probably be created
