### ISSUE TITLE
Forwarding email received on AnonAddy address to someone behind another AnonAddy address fails

### ISSUE THREAD

**Issue by xanoni** [anonaddy/anonaddy#166]
1. Receive email (e.g., newsletter) on abc@anonaddy.me
2. Forward this email to abc@xyz=anonaddy.me@anonaddy.me
3. Email is not received by xyz@anonaddy.me

I also noticed that in the AnonAddy web interface, the "Replies" counter of abc@anonaddy.me is incremented. I assume that it misunderstands the "forward" as a reply.

**Comment by willbrowningme** [comment]
That's because the forwarded message has an "In-Reply-To:" header which AnonAddy checks for.

I've just tested this myself and both work, forwarding a recieved email and also just sending a fresh one from scratch.

In both scenarios I received the email as expected.

Could you email me with more details and the actual aliases used if you are still having this issue?
