### ISSUE TITLE
Email replies coming back as new emails to recipient address and not going to original sender

### ISSUE THREAD

**Issue by jhotmann** [anonaddy/anonaddy#17]
I just upgraded to the Lite subscription and decided to test email replies. When I reply to an email, it never gets sent to the original sender, instead I just get the reply at my recipient address. Also the website shows 0 replies in my stats.

I am using Protonmail as my recipient email provider and have tried with GPG both on and off.

When I reply to an email the recipient address is [Alias]+[long base 16 string]@username.anonaddy.com

**Comment by anonaddy** [comment]
@jhotmann thanks a lot for subscribing! 

I've just added a section to the [FAQ](https://anonaddy.com/faq/) about replying to emails.

When you reply to a forwarded email you need to use the Reply-To: header value that is set on the email. Most email clients and web clients should do this automatically, the only one I know of that sometimes doesn't respect the Reply-To header is Gmail.

An example of one of these headers looks like this:

Reply-To: "sender@example.com" <alias+59fhbf7f1ea374c9182ac0f269m3192501fep210@johndoe.anonaddy.com>

You appear to be using the correct email [Alias]+[hash]@username.anonaddy.com (the bit between the < > above) but I think the issue is that you are missing out the "display name" value of "sender@example.com" above.

This "display name" must also be included when you send your reply as this is compared against the hash value to determine where the reply should be sent.

Please give it another go making sure to include the display name and let me know if you are still having issues.

**Comment by jhotmann** [comment]
Ah very nice. The Protonmail web client does respect the Reply-To header and sends it correctly. I'll submit a ticket for the Protonmail Android app to do the same.

Thanks for your help!
