### ISSUE TITLE
Hardware keys setup is unreliable

### ISSUE THREAD

**Issue by ishristov** [anonaddy/anonaddy#179]
Found 2 issues:

1. I have 1 yubikey for my pc and 1 yubikey for my phone. They are different models and I can't use the pc yubikey on my mobile device or vice versa (due to compatibility issues). So I need to add both of them as a U2F method. The issue is that if I add the 1st yubikey through my pc I am then unable to login via my mobile device to add the 2nd yubikey. There should be an option to enable/disable 2fa WITHOUT deleting the already added yubikeys. Or in other words - I should be able add multiple yubikeys and then enable the 2fa. Should be able to disable 2fa, then enable it and reuse the yubikeys that were added from before.

2. Everytime I add a new yubikey, I get the warning message at the top that shows the "restore backup code". The problem is when I add 2nd, 3rd, etc. yubikey, I get NEW backup code without a clear explanation what happens with the old codes. My understanding is that this backup code should appear once for the first 2fa setup and then show it again only when I disable and reenable the 2fa, not when I am adding MORE keys.

**Comment by willbrowningme** [comment]
Thanks for the feedback, I agree with your points.

I've just pushed a new release that adds the option to toggle each webauthn key as enabled or disabled which addresses your first point.

I've also updated it so that the backup code is only shown when you add your first key and not when you add subsequent keys.
