### ISSUE TITLE
[Feature request] Option to bounce rather than silently discard per alias

### ISSUE THREAD

**Issue by fazy** [anonaddy/anonaddy#188]
Given an alias `alias-1@example.com` and another alias `alias-2@example.com`
When email is sent to `alias-1@example.com` Then I want the email to bounce back to the recipient
And when email is sent to `alias-2@example.com` Then I want the email to be silently dropped
And when email is sent to `alias-3@example.com` Then I want the alias to be automatically created and the email forwarded

In other words: I have a catch-all domain, I would like to keep auto-creation of aliases, but when I want to stop receiving emails, I want to decide what kind of response is given.

For cases where a serious data breach has occurred and all kinds of spam/malware is being received, there is no point in bouncing it.

In other cases there are supposedly legitimate organisations who have not followed applicable privacy laws correctly, but I nevertheless have (or could have) some kind of relationship with. For example, most recruiters, but also many organisations such as insurance companies, retailers, energy companies, travel companies or whatever who I've had legitimate dealings with, but don't do a good job of cleaning up their database. In such cases I might want to bounce emails to send them a message that their data is stale but if they _really_ need to contact me, there is probably another way.

At the moment I can't find a way to achieve this, and actually I am not sure of the difference between the active on/off toggle, delete or forget (especially with respect to auto-creation with a catch-all domain).

**Comment by willbrowningme** [comment]
When an alias is set as inactive (active toggle is off) then it will silently discard any emails sent to it, the sender will not be informed that the email has not reached you.

When an alias has been deleted then it will reject (bounce) any messages sent to it with the following error: `5.7.1 Recipient address rejected: Access denied`, the sender will therefore realise that the message was not delivered.

When you forget an alias it depends on whether it is a shared domain alias (any alias that has a domain that is shared by other users, e.g. *@anonaddy.me) or a standard alias (any alias that had a domain unique to you e.g. *@johndoe.anonaddy.com).

If it is a shared domain alias then it will be completely disassociated from your account. It can never be restored or used again, once a shared domain alias has been forgotten, it will reject any emails sent to it with the same error as above.

If it is a standard alias then it will be completely removed from the database as if it never existed in the first place. If someone sends an email to the alias and you have catch-all enabled then it will be created automatically again.

So in your case with your custom domain all aliases using that domain will be classed as standard aliases because the domain is only used by yourself and is not shared with other users.

So what you describe above is already possible. Let me know if you have any other questions.

**Comment by fazy** [comment]
Thanks, I've got it now. So with a custom domain and catch-all:

Active = forward
Inactive = silently drop
Delete = soft delete, bounce, don't automatically re-create with catch-all
Forget = hard delete, automatically re-create with catch-all

**Comment by willbrowningme** [comment]
Yes that's correct.

**Comment by alexaka1** [comment]
> When an alias is set as inactive (active toggle is off) then it will silently discard any emails sent to it, the sender will not be informed that the email has not reached you.
> 
> When an alias has been deleted then it will reject (bounce) any messages sent to it with the following error: `5.7.1 Recipient address rejected: Access denied`, the sender will therefore realise that the message was not delivered.
> 
> When you forget an alias it depends on whether it is a shared domain alias (any alias that has a domain that is shared by other users, e.g. *@anonaddy.me) or a standard alias (any alias that had a domain unique to you e.g. *@johndoe.anonaddy.com).
> 
> If it is a shared domain alias then it will be completely disassociated from your account. It can never be restored or used again, once a shared domain alias has been forgotten, it will reject any emails sent to it with the same error as above.
> 
> If it is a standard alias then it will be completely removed from the database as if it never existed in the first place. If someone sends an email to the alias and you have catch-all enabled then it will be created automatically again.
> 
> So in your case with your custom domain all aliases using that domain will be classed as standard aliases because the domain is only used by yourself and is not shared with other users.
> 
> So what you describe above is already possible. Let me know if you have any other questions.

Hey @willbrowningme 
This behavior should be reflected somewhere in the docs, either in the FAQ or the help pages. I wasn't able to find this information anywhere else.

**Comment by willbrowningme** [comment]
@alexaka1 I recently added it to the help page under the terminonogly section - https://anonaddy.com/help/

**Comment by alexaka1** [comment]
Ah yes, I see now. I was using the search on the help page, for keywords like forget, deactivate, delete. And only deactivate yielded the "deactivating email aliases" page, which did not contain this information. It might be worth referencing it there too imo.
