### ISSUE TITLE
Emails from noreply@steampowered.com always fail to deliver

### ISSUE THREAD

**Issue by Cwpute** [anonaddy/anonaddy#246]
I can't receive any emails from `noreply@steampowered.com`, as they're stoppped by anonaddy. The issue might be their emails being considered as spam by your spam filter, as it happens quite a lot for many people with different email providers. Not a problem usually as you can take a dump in your spam folder and retrieve those precious mails.

The difference with anonaddy is that there isn't any way to actually see or allow those rejected emails coming from a specific adress once we know they're not spam. At least, any way i'm aware of as a free customer !

I have three questions:

* Why did anonaddy consider emails from `noreply@steampowered.com` as being spam ?
* Is it possible to permanently allow emails from this adress for all anonaddy users ? as it is an official adress for a widely well known organization.
* Will i be able to authorize these emails if i become a paying customer ?

**Comment by ccorneli** [comment]
I just tested this and had no issue.  
So I'm not sure this is something caused by AnonAddy.
My guess is that Steam might have AnonAddy domain on a blacklist and refuse to send?

Details:
I had an old steam account registered with my previous email forwarding service I used a long time ago.  I logged in and just updated the address to point to an AA alias, and the verification codes were successfully received and transfer completed.

Note: I'm using my own domain which could be why it was successful, perhaps Steam is aware AnnonAddy domain is a mail forwarding service and put it on a blacklist which just refuses to send email from their side.   I had that problem with my old forwarding service. Mail from anyone who used MailChimp or other similar contact management software would just never get sent to me. Using my own domain was the primary reason I switched to AA.  Companies like steam are especially sensitive to throwaway/anonymous email services so I wouldn't be surprised if that is the case.

**Comment by Cwpute** [comment]
Thanks for the insight @ccorneli , i'll ask Steam's own client service to see if the problem comes from their side. I assumed that, since i received notifications from AA that i had failed deliveries from this adress, that the problem come from AA. But maybe it doesn't ?

**Comment by ccorneli** [comment]
The paranoid version of my inner-self would probably to leave AA out of the discussion with Steam, so as not to bring their attention to it, and get it added on a black list.. but I guess that would happen anyway as they investigate your provided email.  It definitely would be helpful to find out if they to blacklisting this way.  Am I correct that you are using AA domain and not a custom domain?   Just curious, which approach to alias generation?  (username, UUID, random word.. etc).  Wondering if there might be some special character they aren't properly supporting internally. (although I would doubt it)

**Comment by Cwpute** [comment]
It's really straightforward: it looks like `plainwordsinletters@myname.anonaddy.com`

**Comment by ccorneli** [comment]
Yeah, my money is that Steam put AA on a blacklist and won't send email to it.  I'm guessing there is a way to confirm that, but I don't know how.

**Comment by willbrowningme** [comment]
@Cwpute I cannot see any issue in the logs with messages being delivered from "noreply@steampowered.com".

Could you [send me an email](https://anonaddy.com/contact/) with your exact alias so I can check if any delivery attempt is even being made?
