### ISSUE TITLE
Support 'From' names per domain/alias

### ISSUE THREAD

**Issue by RikudouSage** [anonaddy/anonaddy#279]
This partially relates to #171 but in my case I would like to set the From name per domain or potentially per alias (for my use case per domain is enough but generally it would be best to go by priority in order of `Alias -> Domain -> Username -> Default`.

Would it be possible to add such feature?

I'm willing to help with implementation if you could point me out to a starting point.

**Comment by willbrowningme** [comment]
Thanks, I do plan to add this feature exactly as you describe. I've added this issue to the roadmap.

I'll try to add this as soon as I can.

**Comment by ccorneli** [comment]
I'm not sure I understand this use case exactly as described, but I think my request is similar so adding here instead of creating a new one,  which is:

If I have multiple custom domains, I would like to configure a different default recipient based on domain.
samealias@mydomain1.com -> default1
samealias@mydomain2.com -> default2

**Comment by willbrowningme** [comment]
@ccorneli That is already possible. You can add a default recipient for each domain on the [domains page](https://app.anonaddy.com/domains).

**Comment by ccorneli** [comment]
Oh,  thanks! I don't see how I missed that, it's so obvious!

**Comment by willbrowningme** [comment]
This has been added to the web app now.
