### ISSUE TITLE
bandwidth

### ISSUE THREAD

**Issue by johnbrz** [anonaddy/anonaddy#28]
I'm about to sign the anonaddy but the monthly bandwidth seems very limited.

only 50MB for the whole month?
and 500MB for the best plan?

i don't know how much i use currently, but these amounts seem to be pretty low. Especially if you look at alternatives like simplelogin which offers unlimited width even for the free plan

**Comment by anonaddy** [comment]
Have you been using the service for long? I think you'd be surprised at how many emails can be forwarded for these limits.

I have way over 100 aliases and never go over 20MB per month.

I wrote a small bit about this in the FAQ page - https://anonaddy.com/faq/

> The average email is about 76800 bytes (75KB), this is roughly equivalent to 7,000 words in plain text. So the 10MB monthly allowance would be around 140 emails, the Lite plan's 50MB would be almost 700 emails and the Pro plan's 500MB would be almost 7,000 emails.

That is true that simplelogin offers unlimited on the free plan, however I would personally rather have unlimited aliases and a bandwidth limit vs a small handful of 5 or so aliases and no limit. Since the entire purpose of aliases is to use a different one for every site.

I also plan to add a new Rules page that will allow you to strip attachments and images from aliases to keep your bandwidth usage low.
