### ISSUE TITLE
Feature Request: Allow turning off creating new aliases on the go

### ISSUE THREAD

**Issue by raulmartinez94** [anonaddy/anonaddy#285]
Hi there,

Thank for such amazing project. Is it possible to enable an option to toggle on/off the creation of new aliases on the go? For example, turn off creating a new alias after it receives it first email, this is because if one of my aliases is breached, whoever knows my subdomain per say name.anonaddy.com can still send me new emails by just adding a random word prior the "@" symbol. I know we can also create generic aliases with anonaddy.me but it just makes it hard to remember the alias and it would be wonderful if a functionality of simply turning off the creation of new aliases on the go can be enabled. Thank you for your consideration.

**Comment by willbrowningme** [comment]
This feature is already available, in order to turn off aliases being automatically created on-the-fly you can visit the settings page and disable "Catch-All" functionality for your main account's username. This is a feature available on paid plans.

This will mean that any alias that uses your username subdomains eg. *@username.anonaddy.com will need to be created beforehand in order to forward messages.

You can also turn off catch-all for your additional usernames on the usernames page and for your custom domains on the domains page.
