### ISSUE TITLE
Something to let GMail disable phishing alerts on forwarded emails?

### ISSUE THREAD

**Issue by W3LLD0NE** [anonaddy/anonaddy#290]
Using AnonAddy for PayPal account (with a final recipient set to GMail address).
Most emails forwarded are marked by Google as phishing (not even spam). The phishing alert removes all the links (and maybe more) from email, which is critical when some action is required (confirm email, restore password etc.).

Any rules to follow to minimize alerts? I'm constantly telling Google the letters are not spam/fishing, but some are just marked as 'suspicious' (not phishing) **without** a button to reverse that, so the email stays broken.

**Comment by willbrowningme** [comment]
This because Google scans the emails and finds references to "PayPal" and immediately assumes it is an attempt to impersonate them. The best option is to enable PGP encryption to prevent Google from scanning the contents.

I will also add the option to remove any reference to "PayPal" in the display From soon.
