### ISSUE TITLE
Send From feature using mailer@ instead of alias

### ISSUE THREAD

**Issue by ThHareau** [anonaddy/anonaddy#305]
Hey, 

I'm trying to use the send from feature, however this is not working as expected. 

I've sent the email using the following recipient: "alias+myemail=maindomain.tld@domain.tld". 

When I connect to "myemail@maindomain.tld", I do receive the email, however it is not sent from "alias@domain.tld" but instead from "My Email <mailer@anonaddy.me>". When I look in the headers, I see the following: 

```
From: My Name <mailer@anonaddy.me>
Reply-To: My Name <alias@domain.tld>
```

I noticed something odd in the send headers; I don't know if it is relevant: 

```
To: alias+myemail=maindomain.tld@domain.tld <alias+myemail=maindomain.tld@domain.tld>
```

If needed I can provide more information, but I'd rather not publish personal information here if possible.

**Comment by willbrowningme** [comment]
It sounds to me like your custom domain has not been verified for sending which is why the messages have to be sent from "mailer@anonaddy.me" instead of your domain's aliases (otherwise they would fail SPF, DKIM, DMARC checks and be rejected).

Please go to the domains page and make sure you see a green check in the "Verified Records" column, if not then click "Recheck" and add the correct ones. If you are still having issues then please [send me an email](https://anonaddy.com/contact/).

**Comment by ThHareau** [comment]
You are correct, I had to click on recheck and it is now working as expected. Thanks a lot
