### ISSUE TITLE
Create alias non-random for custom domain

### ISSUE THREAD

**Issue by stefanschramek** [anonaddy/anonaddy#31]
Hi,

it would be nice to have a 3rd option for custom domains which allows creation of defined aliases and not just random!
What do you think about it?

Thanks
Stefan

**Comment by anonaddy** [comment]
If you're using a custom domain you do not need to generate an alias beforehand to use it. 

The custom domains behave like a catch-all and aliases are automatically created as soon as they receive their first email.

I do agree though, it might be nice to have the option to create these from the site/extension so that you can update the recipient, description etc. before using it. So I'll add this to my to do list, thanks.

**Comment by stefanschramek** [comment]
Thanks for clarifying this!
