### ISSUE TITLE
[Feature request] Store or forward blocked emails

### ISSUE THREAD

**Issue by Nicicalu** [anonaddy/anonaddy#323]
I have a lot of blocked aliases. I don't need to read the emails.

**But what if I need to read a email from a blocked alias?**
It would still be great if you could choose to forward blocked emails to a special "spam-email" or to store them on the server somewhere.

**Comment by willbrowningme** [comment]
It is not possible to read a blocked email sent to any alias since it is never even accepted by the mail server so could not be stored even if I wanted to.

You can just add a special "spam-email" as a recipient and then instead of deactivating or deleted an alias you don't want anymore, just add that recipient to it instead. Then all messages you don't care about will go to your "spam-email".

**Comment by Nicicalu** [comment]
@willbrowningme Oh, makes sense! Thank you very much!
