### ISSUE TITLE
Invalid Recipient

### ISSUE THREAD

**Issue by gatordoc** [anonaddy/anonaddy#327]
I am no longer able to add a new alias.  On doing so, it tells me "Error: Invalid Recipient".  I've tried multiple with same error.

When I check recipients, all are green and verified.  Same with checking domain.  I've tried logging out and back in.  Tried in incognito.  We are on a paid plan.  Not sure what else to try.  

<img width="452" alt="Screen Shot 2022-08-24 at 12 07 29 AM" src="https://user-images.githubusercontent.com/74688286/186326854-04ad215a-deca-4802-8e3c-588c8ea2a0fa.png">

**Comment by willbrowningme** [comment]
This is due to the face that I updated from vue 2 to vue 3 yesterday and had to change the multi-select component that is used to select recipients.

Please try clearing your web browser's cache and it is likely still loading the old assets which is why you are seeing that error.

The assets are versioned e.g `/js/app.js?id=04676ef6a1c077f1a66a01a70e54fca7` so I'm not sure why it hasn't automatically loaded the new assets for some people.

**Comment by gatordoc** [comment]
Tried it again just now.  Clearing cache didn't help.  But I did find a way around it.  If I create the alias without a recipient.  Then add the recipient after.  It works.

**Comment by willbrowningme** [comment]
This was indeed a bug, I've just pushed a new release that fixes it - https://github.com/anonaddy/anonaddy/releases/tag/v0.13.7

Thanks for bringing it to my attention.
