### ISSUE TITLE
What to do when port 25 is closed

### ISSUE THREAD

**Issue by ririko5834** [anonaddy/anonaddy#342]
I tried to install anonaddy in docker on oracle free tier instance but it doesn't work - getting connection timeout error logs in console from postfix, port 25 is closed. I have tried to also open it on the firewall on oracle dashboard but it doesn't work.
What should I do?
Is there a way to use a different port?

**Comment by willbrowningme** [comment]
I imagine Oracle have blocked port 25 on their free tier in order to prevent mail spam bots and abuse. You can try contacting them to see if this is the case.

You won't be able to receive emails from other mail servers without port 25 open as they will look up the receiving domain's MX record and then attempt to connect to port 25 on that server.

**Comment by ririko5834** [comment]
I contated them and they dont want to open it

**Comment by ririko5834** [comment]
Is there a way to use third-party smtp relay?

**Comment by willbrowningme** [comment]
You can use any mail driver compatible with Laravel - https://laravel.com/docs/9.x/mail#driver-prerequisites

But with port 25 closed you still will not be able to accept messages from other mail servers.

**Comment by modaresimr** [comment]
In oracle you can receive email from port 25 but you can not send email to port 25

Is there any solution to resolve this situation?

**Comment by ririko5834** [comment]
I host my instance on Contabo
