### ISSUE TITLE
Inline pgp emails to Proton are empty.

### ISSUE THREAD

**Issue by mannp** [anonaddy/anonaddy#380]
I have configured AA with the pgp key for my protonmail receiving account and the emails encrypt fine, but they are completely blank?

Not sure what I am missing.

Thanks.

**Comment by willbrowningme** [comment]
Due to the way inline encryption works only the plain text part of the messages can be properly encrypted and decrypted.

The tooltip on the recipients page for that column states:

"Use inline (PGP/Inline) instead of PGP/MIME encryption for forwarded messages. Please Note: This will ONLY encrypt and forward the plain text content!"

So your forwarded email must not have had any plain text content.

Please try again making sure to send only plain text.

Most people will not use this setting, I would recommend turning it off if you want to receive html or mixed type messages.

**Comment by mannp** [comment]
`This will ONLY encrypt and forward the plain text content!"`

I read it but it was meaningless in the context of signing up for companies emails etc.

How would I know there content before receiving it? What about partial content.

`Please Note: Turn this off if you wish to receive html or mixed type messages. Turn on for plain text ONLY`

**Comment by willbrowningme** [comment]
It was added on a few user requests who had special uses cases where they only required plain text content. I'll update the note to make it more clear.

**Comment by mannp** [comment]
> It was added on a few user requests who had special uses cases where they only required plain text content. I'll update the note to make it more clear.

Thanks, an update to the note would be a great help to understand directly what it does 👍🏻
