### ISSUE TITLE
[Bug] Aliases forgotten return and are "recreated" after an email is sent to it.

### ISSUE THREAD

**Issue by ejohnguia** [anonaddy/anonaddy#394]
On the [webapp](https://app.anonaddy.com/), I would use a Standard Aliase and later click on the "Forget" option. After a few days later, an email would show up from that forgotten email and I would see the alias has been recreated in my account.

**Comment by willbrowningme** [comment]
This is not a bug, it is intended behaviour.

When you forget an alias the modal states "If it is a standard alias then it can be created again since it will be as if it never existed."

If you have catch-all enabled for that alias' domain then it can be automatically created again as soon as someone sends an email to it.

You should either:
- turn off catch-all for that domain / subdomain
- delete the alias instead.
