### ISSUE TITLE
Disallow inclusion of plus address when creating alias.

### ISSUE THREAD

**Issue by rokejulianlockhart** [anonaddy/anonaddy#421]
I accidentally included a plus address in an alias that I created. This hasn't been a problem, since sending mail with a different plus address (obviously as replacement to the original rather than appended) and without any plus address deliver mail to the base address without problem, but I see no benefit to including it in the original address in the interface, whereas it certainly may cause confusion, as it did for me, since the mail delivery subsystem treats it as one would probably hope.

Summarily:
1. [ ] disallow creating base-address+plus-address@anonaddy.com
2. [ ] correct to base-address@anonaddy.com
3. (but do not modify current direction functionality)

I don't consider this to be important, but I certainly believe that it's worth implementing.

**Comment by willbrowningme** [comment]
The + extension of an alias is recorded in a separate database column when a standard alias is first created. 

This is mainly so that you do not forget that you included one when first making the alias.

If you created a new alias `first+ext@johndoe.anonaddy.com` as your login for a site but then AnonAddy removed the `+ext` bit and didn't record it then you may later try to login with `first@johndoe.anonaddy.com` forgetting that you had used an extension.

**Comment by willbrowningme** [comment]
It is not overridden if you send a message to the same alias with a different plus extension. Only the one that was present when it was first created it stored.

If I prevent the creation of new ones with any extension then their will be no record of the full email used when creating a login etc.

**Comment by willbrowningme** [comment]
With subaddressing (plus extensions) the underlying email address is the same. So in the eyes of AnonAddy `username+one@anonaddy.com` is the same alias as `username+two@anonaddy.com`. 

It doesn't matter what extension you add, the message will still go to the same underlying alias `username@anonaddy.com`.

Appending multiple extensions and sending to `username+one+two@anonaddy.com` is not the expected behaviour.

You can inspect the headers of any forwarded message and view the `X-AnonAddy-Original-To:` to see if it was sent to the alias including a plus extension.

[https://www.codetwo.com/admins-blog/plus-addressing/](https://www.codetwo.com/admins-blog/plus-addressing/)

Many users choose to use plus extensions for their aliases and if I disabled it then it would also break the feature described here [https://anonaddy.com/blog/add-recipients-to-aliases-at-creation-and-new-uuid-aliases/](https://anonaddy.com/blog/add-recipients-to-aliases-at-creation-and-new-uuid-aliases/).

**Comment by rokejulianlockhart** [comment]
> Many users choose to use plus extensions for their aliases and if I disabled it then it would also break the feature described here [anonaddy.com/blog/add-recipients-to-aliases-at-creation-and-new-uuid-aliases](https://anonaddy.com/blog/add-recipients-to-aliases-at-creation-and-new-uuid-aliases/).

Alright. I didn't know of that nifty feature. Thanks.
