### ISSUE TITLE
Unable to register if "Real Email Address" appears in "Recipients" of another account.

### ISSUE THREAD

**Issue by DavidPesticcio** [anonaddy/anonaddy#440]
During registration, if the "Your Real Email Address" appears in the "Recipients" of an existing account you cannot use it to register.

Use Case:
1. Register using a test "Real Email Address"
2. Create alias for recipient
3. Testing goes okay, now setup a non-test account
4. Register using a non-test "Real Email Address"
5. Failed to register "Real Email Address" already in use

If any recipient email address (see point 2) exists under the test "Real Email Address" account, it will prevent registration of the non-test "Real Email Address"

Is this a bug or intentional?

**Comment by willbrowningme** [comment]
This is intentional as otherwise functions such as the username reminder and looking up users via their email address would not work correctly.

If this was not in place there would also be nothing to stop a user creating a large number of accounts using the same email which would be against the terms of the service.

You can either delete your test account or change the email address on your test account to allow you to use it for your new non-test one.
