### ISSUE TITLE
SSL covering '4wrd.cc' (no SNI)

### ISSUE THREAD

**Issue by RixzZ** [anonaddy/anonaddy#45]
Hello.

I just recently find about AnonAddy and looks like a great project. I'm considering becoming a paid user after trying out today.

While informing myself about the service using your website, I saw the part about security and where you link the SSL Labs test to analyse the main domain.
Everything seems right, except that SSL requests to the IP address without SNI come back with a wildcard SSL certificate for '4wrd.cc'.

I guess is something related to the project, but I have to ask: does the server host other unrelated projects? Anything that could be a security problem for AnonAddy?

Regards.

**Comment by willbrowningme** [comment]
Hi,

Thanks a lot! 

Yes that is correct, all domains used on the site have wildcard SSL certificates issued by Let's Encrypt. The reason for this is so that they can all be used for a user's unique username subdomain e.g. johndoe.anonaddy.me or johndoe.4wrd.cc etc.

The server only hosts anonaddy.com and app.anonaddy.com, there is nothing unrelated to the service on there.

Let me know if you have any other questions.
