### ISSUE TITLE
[Feature Request] Recycle usernames of deleted accounts with no email received

### ISSUE THREAD

**Issue by Patrick-Ze** [anonaddy/anonaddy#452]
*This issue was translated by ChatGPT. Feel free to ask me to provide more information if necessary.*

I registered an account today with my favorite username. However, I soon realized that I needed to change the associated email address. Unfortunately, I couldn't find a way to do so, and as a result, I decided to delete my account. During the deletion process, I noticed a prompt informing me that the username would no longer be available for use.

In my opinion, this prompt seems unreasonable since I never received any emails on the account. Therefore, the username can be safely recycled to avoid unnecessary consumption of username resources.

I suggest adding a feature that recycles usernames of deleted accounts that have never received any email communication. This will enable these usernames to be added to the available usernames list and be used by other users.

**Comment by ririko5834** [comment]
Good idea

**Comment by willbrowningme** [comment]
It's not as straight forward as that since an account could have hundreds of aliases that use their username subdomain (*@username.anonaddy.com) but then forget them all. This completely removes them as if they never existed.

Clearly this username should not be released since all those previous aliases could be recreated for a different user.

**Comment by rokejulianlockhart** [comment]
Better yet, if the user *wants* to, I believe that they should be able to choose to make their username available again upon account deletion, rather than be prevented from doing so if messages have been received by the account. This would be useful if they're confident that they've removed any account associations with that address.

**Comment by ririko5834** [comment]
It should be possible to re-create deleted and forgotten alias on your account domain and on custom domains only, not for shared domains.

**Comment by w3lld0ne** [comment]
Consider situation where some evil user does some malicious actions using his emails, then deletes his account and marks it's username free for reuse. Would you like to actually reuse this name, knowing nothing about it's previous owner and what he did with that mail?
At least there should be a clearly visible mark "Previously used!" for these sorts of usernames.

**Comment by sealldeveloper** [comment]
Furthermore if it hasn't been mentioned. The email could be used somewhere and then an email has not been received yet, delete the alias and have it marked for re-use, that would then land on the user who gets the new alias. The usernames should stay single-use.

**Comment by rokejulianlockhart** [comment]
@Patrick-Ze, perhaps re-close and unplanned rather than completed then?

**Comment by Patrick-Ze** [comment]
> @Patrick-Ze, perhaps re-close as unplanned rather than completed then?

Sorry, I'm not very familiar with github. It's updated.
