### ISSUE TITLE
A recipient with that email already exists

### ISSUE THREAD

**Issue by lawfulsoftware** [anonaddy/anonaddy#468]
I am using TickTick which generates a unique email address in the format: todo+yhsmgmdt85e9@mail.ticktick.com

It seems that AnonAddy treats this as todo@mail.ticktick.com and disregards everything after the +.  Is there a workaround?

**Comment by willbrowningme** [comment]
That's correct, hi+abc@example.com is seen as the same email as hi+xyz@example.com because fundamentally it is.

This is partly to prevent abuse of users creating large numbers of free accounts using the same email which is against the terms of service.

I'm afraid I don't have any plans to change this. If you have a paid subscription send me an email and I'll check your account.
