### ISSUE TITLE
Gmail banner message about spoofing or improperly forwarding

### ISSUE THREAD

**Issue by TitaniumCoder477** [anonaddy/anonaddy#579]
I created a subdomain alias for my domain (hazaqames.com) and signed up on a website. I received the email, but it's the first time I noticed the banner that says, "Warning: This email may be spoofed or improperly forwarded, please check the 'X-AnonAddy-Authentication-Results' header." I google'd this and reached https://addy.io/self-hosting/ which doesn't apply to me since I'm a paid subscriber, not a self-hoster, of this product. Please advise.

P.S. My domain's Verified Records column is green, no issues there.

**Comment by willbrowningme** [comment]
That warning banner is added by addy.io when it forwards an email to you if that email failed its authentication checks (DMARC).

It is added in order to protect you from any potential phishing attempts or spoofed emails.

The sender has most likely just misconfigured their SPF and/or DKIM settings which is why that banner has been added.

If you look at the email headers for that email and find the one called `X-AnonAddy-Authentication-Results` then this will contain information on what exactly did not pass the checks.
