### ISSUE TITLE
Failed delivery recursion

### ISSUE THREAD

**Issue by Iizuki** [anonaddy/anonaddy#585]
I just received a notification mail about a failed delivery (from the official addy.io instance). I went to check it and saw this:

![Addy_failed_deliveries](https://github.com/anonaddy/anonaddy/assets/36295229/8a1e17a2-ac9e-4b3e-abfe-ff49e9116bd2)

The bottom entry is a real delivery fail, and in so far as I can tell, all the rest are delivery fail notifications about the previous delivery fail notification which failed to deliver, until one finally got through.

The alias in question is not using my default recipient. It has a single other recipient set.

So what likely transpired, was that the particular recipient was out of service for a moment, and Addy just kept spamming it about failed deliveries. 

I feel like there should be a bit more logic in where to send the failed delivery notice. It's not very fruitful to send it to the address which just a moment ago failed to receive mail. _I would expect the failure notification to be sent to my default recipient,_ and the settings page gives this impression as well.

```text
This is your account's default recipient email address, it is used for all general email notifications.
```

Although if it's my default recipient failing to receive mail, then it probably should be sent to some other recipient.

**Comment by willbrowningme** [comment]
Thanks, it looks like this was caused because Postfix restarted itself on the mail2.anonaddy.me mail server and then failed to start up again correctly which is why those errors were shown, incoming messages were deferred and should have been automatically retried by the senders.

This was resolved earlier today and messages should be coming through as normal.

The recursion of saving the failed deliveries was indeed a bug that I have now fixed.
