### ISSUE TITLE
[Feature Request] Add ability to automatically decrypt outgoing messages

### ISSUE THREAD

**Issue by Pr0prioceptid** [anonaddy/anonaddy#599]
Hello,
It would be nice if I could encrypt my mail locally with the anonaddy public key before sending and have anonaddy decrypt it for me before it gets to the person I'm trying to send mail to.

This is for when I'd like to hide the contents of my outgoing mail from my email provider, but the person I'm sending to isn't interested in providing their public key.

**Comment by willbrowningme** [comment]
I have this working and I'm currently beta testing it on addy.io.

Please [drop me an email](https://addy.io/contact/) with your username if you'd like to help test it out so that I can add you as a beta tester.

**Comment by willbrowningme** [comment]
In order to help beta test this you simply need to encrypt a reply/send to one of your aliases using the `no-reply@addy.io` public key  (fingerprint - `26A987650243B28802524E2F809FD0D502E2F695`). You can get the key on [https://keys.openpgp.org](https://keys.openpgp.org/search?q=26A987650243B28802524E2F809FD0D502E2F695).

When the message arrives at the addy.io server, it will attempt to decrypt it using the corresponding private key. If it is successful then it will replace the message data with the decrypted contents and send it on to the correct destination.

If you are using Mozilla Thunderbird then you will need to use their pgp alias rules configuration - [https://support.mozilla.org/en-US/kb/openpgp-recipient-alias-configuration](https://support.mozilla.org/en-US/kb/openpgp-recipient-alias-configuration), this is because by default they do not allow you to encrypt an email using a public key that does not match the receiver's identity.

Here's an example config that you can use for your `openpgp_alias_to_keys.json`:

```json
{
  "description": "Thunderbird OpenPGP Alias Rules",
  "rules": [
    {
      "domain": "anonaddy.me",
      "keys": [
        {
          "description": "Testing decrypt replies/sends on addy.io",
          "fingerprint": "26A987650243B28802524E2F809FD0D502E2F695"
        }
      ]
    }
  ]
}
```

This will allow you to encrypt all messages sent to aliases `*@anonaddy.me` using the `no-reply@addy.io` public key.

**Comment by willbrowningme** [comment]
It will also remove any attached PGP keys (`Content-Type: application/pgp-keys`) when decrypting the reply/send in order to prevent you accidentally exposing your real email.

**Comment by lawmanuk** [comment]
What happens when we want our PGP public key to go to recipient so they can write back?

2 problems I've found.

1) Addy doesn't give option to keep them.

2) Thunderbird doesn't allow assigning key to email account without an email address in identity.  Ideally I'd like to create a pgp key without email in identity the import to thunderbird pgp manager, but it doesn't let you assign to account if identity has no email.   Claws email lets you do this but its not great in many other ways.   Don't want to use console Neomutt and others as too many limitations in the modern world with graphics etc.   

Is there a solution to above?  Especially (2)?

Thanks

**Comment by lawmanuk** [comment]
when deleting pgp key from replies/sends does it also remove from the autocrypt headers?
