### ISSUE TITLE
Email from now `at` instead of `@`.

### ISSUE THREAD

**Issue by luckydonald** [anonaddy/anonaddy#602]
I upgraded from `0.14.0` to `1.0.4`, and for some reason the email format changed, and I'm not able to change it back.

<img width="1408" alt="Screenshot 2024-02-26 at 22 39 43" src="https://github.com/anonaddy/anonaddy/assets/2737108/2469c816-c80a-476a-b6ba-6ccbecf79609">

This is especially annoying as about 100 email rules in my Mail.app depend on the original name being in the name of the email.

----

Additionally I think,
> Some Service  'some at service.de'

is simply not as readable as

> Some Service 'some<b></b>@service.de'

---

And,
> some<b></b>@service.de 'some<b></b>@service.de'

is also better to read than

> some at service.de

---
The changelog said that the _default_ format was changed, but there's no way to change back.

**Comment by willbrowningme** [comment]
Thanks, I've just pushed a commit to bring that back.

**Comment by luckydonald** [comment]
Thank you.

**Comment by JensSpanier** [comment]
Is it intentional that this option is not available on app.addy.io? On my selfhosted instance the option is available.

app.addy.io:
<img width="1277" alt="grafik" src="https://github.com/anonaddy/anonaddy/assets/42373861/34ccae08-fe04-45c0-b5bb-47859a0ad2ef">

selfhosted:
<img width="1279" alt="Bildschirmfoto 2024-03-30 um 12 12 54" src="https://github.com/anonaddy/anonaddy/assets/42373861/77647baf-9d16-4d46-8d64-eb501fb7b3b0">

**Comment by willbrowningme** [comment]
Yes it is intentional because it can negatively impact email delivery resulting in more messages landing in spam or being rejected.

**Comment by luckydonald** [comment]
Probably the anonaddy to private mail side, not anonaddy with external, right?
