### ISSUE TITLE
[Bug] Adding a domain excludes existing aliases

### ISSUE THREAD

**Issue by luckydonald** [anonaddy/anonaddy#609]
I moved my domain and added the original domain as an alias domain but the domain overview lists zero domains for @firstdomain.com.

Instead, it ideally should list all ~100 existing email aliases.
Not ideal, but still an improvement would be to have an "other" category, where those mails in the wrong categorises are listed.

<br>

**Steps to reproduce:**
1. create host at app.firstdomain.com, with firstdomain.com accepting mail vial MX @.
2. Send a few mails to test@firstdomain.com, test2@firstdomain.com, test3@firstdomain.com, etc.
2. move instance to app.newdomain.com
3. add firstdomain.com as an external domain to an account, going through MX verification and setting updated DNS entries correctly as indicated in the GUI.
4. observe that test@firstdomain.com, test2@firstdomain.com, test3@firstdomain.com, etc. are listed in the overview, but not included in the domain filter for firstdomain.com, and not included in the count either.

**Comment by willbrowningme** [comment]
That is because they were created when firstdomain.com was a root domain (can be used by all users) and now you've changed it to a custom domain added to one user's account.

You need to update the database columns for those aliases:

Setting the `aliasable_id` to the custom domain's ID and the `aliasable_type` to `App\Models\Domain` then they will "belong" to that custom domain.

This is an edge case not a bug.
