### ISSUE TITLE
What does `alias` mean in the Rules page?

### ISSUE THREAD

**Issue by businessBoris** [anonaddy/anonaddy#651]
I can create a rule - `if the alias contains ..`

What does `alias` refer to in this context? Is it just the alias? Does it include the description?
I'd like to do something if the alias `Description` contains something because that can be changed.

For example, the (end) email provider can delete the mail after 1 day if the `Description` contains a code.
For email that is mostly spam but sometimes contains useful things so can't be removed as an alias or unsubscribed directly.

Thank you in advance.

**Comment by willbrowningme** [comment]
It is just the alias email address e.g. `alias@johndoe.anonaddy.com`.

So in this case saying `if the alias contains "johndoe"` then this condition would be true.

I've just updated the rules page so that is states `alias email` to make it more clear. I've also added `alias description` so you can match that now too as well.

**Comment by businessBoris** [comment]
Would you please consider including the description in the rules search? Either separately or together?

**Comment by willbrowningme** [comment]
I'm not sure what you mean? The description of what, the alias? And do you mean the top search bar where you can search your rules by their name?

**Comment by businessBoris** [comment]
Yes. "If the alias description contains .. ". 
It's there now! 
Thank you very much!
Closing.
