### ISSUE TITLE
discogs.com blocks all Anonaddy domains

### ISSUE THREAD

**Issue by in-plaintext** [anonaddy/anonaddy#690]
`https://www.discogs.com/users/change_email`

Discogs doesn't allow using the following domains:

```
anonaddy.com
anonaddy.me
addymail.com
addy.io
username.anonaddy.com
username.anonaddy.me
username.addy.io
```

---

[Tutanota](https://github.com/tutao/tutanota) is accepted at the time.

**Comment by willbrowningme** [comment]
Thanks for the report.  Some sites do use third-party email validation services that block addy.io domain names.

Unfortunately this is out of my control which is why I ask users not to publicly list any of the paid alias domain names.

One option would be to contact the service and ask them to remove the block, explaining that addy.io aliases are not the same as disposable, temporary email services.

I'm closing this issue as it doesn't make sense to have an issues for every single site that blocks alias domains.

I may start maintaining a list of all services that do block the alias domains though.

**Comment by in-plaintext** [comment]
Sorry for posting the exclusive domains.

> I may start maintaining a list of all services that do block the alias domains though.

@willbrowningme Please do so, a single Github discussion to crowdsource all such services, for instance.
