### ISSUE TITLE
frequent new failed delivery on addy.io

### ISSUE THREAD

**Issue by asanghc** [anonaddy/anonaddy#696]
Is anonaddy doing some kind of spam detection and purposely not forwarding positives?
Does anonaddy have some sort of peering problem with yandex?
Is this just a ploy to get us to subscribe so we can see the messages that were not forwarded?

**Comment by samuraiu** [comment]
The problem is that this failed delivery is more of a recent problem, i also receive quite few failed deliveries each day. 
It is mostly on mailer.me or addy.to and 4wrd.cc
I have spent quite some time on setting this up, and i am getting annoyed that i have to look for an mail on your service. 

For ever mail i see Blocked

smtp; 554-5.7.1 Service unavailable; Sender address [b_onsww4tznv3wiylsgbzq_mi2tccccgbqwm@addy.to] blocked using multi.surbl.org; Blocked, addy.to on lists [dm], See: http://www.surbl.org/lists.html 554 5.7.1 See mail filtering policies here: http://www.namesilo.com/Support/Email-Filtering

So would like to know, whose problem it is and how do i fix it?

**Comment by willbrowningme** [comment]
@samuraiu That rejection message is because NameSilo is choosing to use SURBL's DM list and is blocking any domain that is on that list, even if they are listed there incorrectly.

I have already contacted SURBL a number of times to have those domains removed but they have not responded.

I have also just contacted NameSilo to request that they do not block messages just because a domain is on that DM list from SURBL. It may help if more people contact NameSilo to request this too.

The addy.io, addymail.com and 4wrd.cc domains are not on that list so you shouldn't have a problem using them. You can check a domain here - [https://www.surbl.org/surbl-analysis](https://www.surbl.org/surbl-analysis)

**Comment by samuraiu** [comment]
Thanks for explanation, i have contacted Namesilo as well and SURBL has a message  for both domains

 addy.to is listed in DM
A ticket for list removal of this domain is already in our queue

**Comment by willbrowningme** [comment]
Thanks for contacting NameSilo too.

That ticket already in the queue for SURBL was created by myself many many months ago but no action has been taken on it.
