### ISSUE TITLE
Purpose of admin username?

### ISSUE THREAD

**Issue by techied** [anonaddy/anonaddy#75]
What is the purpose of ANONADDY_ADMIN_USERNAME in .env? Is there an administration frontend that can be accessed somehow?

**Comment by KevinRoebert** [comment]
> What is the purpose of ANONADDY_ADMIN_USERNAME in .env? Is there an administration frontend that can be accessed somehow?

As far as I understood, the admin will receive all emails, that can't be delivered to an existing alias/username. So something like a catch-all.

E.g. you have the domain example.com, the user John, and Doe. John is an admin. I've you send an email to something@example.com, normally no user/alias would receive this mail because there is no alias for this mail. Therefore, John (admin) will receive this mail.

**Comment by KevinRoebert** [comment]
The doc states:

> ANONADDY_ADMIN_USERNAME: If set this value will be used and allow you to receive forwarded emails at the root domain

**Comment by willbrowningme** [comment]
That's correct, there isn't any administration panel that can be accessed. Perhaps I should have chosen a better name for it.

The admin username (if set) will act as a catch-all for the root domains (those set in `ANONADDY_ALL_DOMAINS`). 

So if one of your domains was example.com and an email came in for random@example.com but this alias did not exist in the database, then if you had the admin username set it will be automatically created and forwarded.
